# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [26]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [27]:
import numpy as np

**2. Print the numpy version and the configuration** Zach

In [28]:
print("The numpy version: {}".format(np.__version__))
np.show_config()

The numpy version: 1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Greg/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Greg/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Greg/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.11

**3. Create a 1D array of zeros of size 10 of type float32** Greg

In [29]:
Z = np.zeros((10,), dtype='float32')
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4. Print the memory size of the array below** Michael

In [30]:
# Z = np.zeros((32,12)) may want to remove this? just confirming
# Include your solution below
print(Z.itemsize)

4


**5. Create a 1D array with values ranging from 10 to 58** Meet

In [31]:
np.arange(10,59)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58])

**6. Reverse the order of the values in the vector (first element becomes last)** Brandon

In [32]:
a = np.arange(10)
# Include your solution below
# Uses a negative step to reverse the order
a = a[::-1]
print(a)

[9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8** Zach

In [33]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [34]:
#Alternate solution using reshape for question 7 (useful for a large range of values):
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix** Greg

In [35]:
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** Michael

In [36]:
Z = np.random.random((10,11))
# Include your solution below
Z_columns = Z.shape[1]
print(Z[:, :].max(axis = 0))

[0.95327095 0.84776247 0.91251863 0.97043272 0.98977559 0.83877773
 0.92442476 0.9014428  0.94375432 0.95800386 0.95773372]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else** Meet

In [37]:
x = np.ones((7,7))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.** Brandon

In [38]:
Z = np.ones((5,5))
# Include your solution below
# Uses np.pad to add additional rows and columns
Z = np.pad(Z, (1,1))
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**12. Extract the integer part of the random array of positive numbers below** Zach

In [39]:
Z = np.random.uniform(0,10,10)
# Include your solution below
print(Z) 
Z=Z.astype(int)
print(Z)

[8.0287117  1.79471898 1.09478221 7.23979387 7.99532448 9.28746484
 0.52302213 0.75585447 5.01581146 5.62265985]
[8 1 1 7 7 9 0 0 5 5]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])** Greg

*Hint:* consider using NumPy broadcasting or the tile function*

In [40]:
a = np.array([0,1,2,3,4])
A = np.tile(a, (5, 1))
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)** Michael

*Hint: Consider using the linspace function*

In [41]:
Z = np.linspace(0,1,12)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it** Meet

In [42]:
vector = np.random.randint(10,size=10)
X = np.sort(vector)
print(X)

[0 2 3 3 6 6 7 7 7 8]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)** Brandon

In [43]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below
# Uses np.sqrt and np.arctan to convert the arrays to polar coordinates
print("X-array: ", X)
print("Y-array: ", Y)
R = np.sqrt(X**2 + Y**2)
T = np.arctan(Y/X)
print("R-array: ", R)
print("T-array: ", T)

X-array:  [0.95224445 0.09452155 0.71238747 0.87722571 0.80766448 0.89482972
 0.62546641 0.24189652 0.54977555 0.80242772]
Y-array:  [0.14232307 0.46678416 0.85370558 0.71526952 0.37320812 0.95694515
 0.64772062 0.41864436 0.75564196 0.54783725]
R-array:  [0.96282155 0.4762581  1.11189438 1.13187253 0.88972254 1.31013902
 0.9004167  0.48350494 0.93447735 0.9716048 ]
T-array:  [0.14836242 1.37100269 0.87539052 0.68404699 0.43285669 0.81892932
 0.80287552 1.0468535  0.94181158 0.59903749]


**17. Create random vector of size 10 and replace the maximum value by 0** Zach

In [44]:
a = np.random.rand(10) # creating vector of 10 random numbers
print(a)  
a = np.where(a == np.amax(a, axis = 0), 0, a) # replacing value with 0 if condition (i.e. is maximum value) is met 
print(a)


[0.123637   0.10784327 0.87858732 0.44028637 0.45523497 0.47737063
 0.25709718 0.91246028 0.50602161 0.09018425]
[0.123637   0.10784327 0.87858732 0.44028637 0.45523497 0.47737063
 0.25709718 0.         0.50602161 0.09018425]


**18. Find the nearest value from a given value (z) in an array (Z)** Greg

In [45]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below

print(f'Array Z: {Z}')

index = np.argmin(np.absolute(Z-z))
nearest = Z[index]

print(f'Nearest value to z={z} is {nearest} at index {index} of Z.')

Array Z: [0.06315309 0.26605395 0.80927917 0.08365633 0.18234556 0.47147443
 0.71896534 0.81096833 0.67888787 0.67940032]
Nearest value to z=0.5 is 0.4714744342942119 at index 5 of Z.


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?** Michael

In [46]:
Z = np.arange(5)[::-1]
# Include your solution below
Z_0 = np.zeros(len(Z) + (len(Z)-1)*3)
Z_0[::3+1] = Z 
print(Z_0)
#Fix inital array??

[4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1. 0. 0. 0. 0.]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)** Meet

In [47]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below
B_reshape = np.reshape(B,(5,5,1))
np.multiply(A,B_reshape)

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

**21. Swap the first and second rows of the 2D array below** Brandon

In [48]:
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution below
# Selects specific rows and swaps the order of them
W[[0,1]] = W[[1,0]]
print(W)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array** Zach

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="../Figures/bbox.png" width="150" /> 

In [49]:
def bbox(img):
    #include your solution below

    # numpy's nonzero function returns an array of tuples that correspond with the indices of each non-zero value in each dimension.
    # The values of the input array are returned in a row-major, C-style order.
    r1=np.nonzero(img)[0][0]-1 # finds the first row that a non-zero value exists in, and subtracts 1 to get the enveloping row 
    c1=np.nonzero(img)[1][0]-1 
    r2=np.nonzero(img)[0][-1]+1 
    c2=np.max(np.nonzero(img)[1])+1 # Due to row-major order, we need to find the max value for the column tuple and then add 1 to get enveloping column 
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0

# --- the code below was used to test ---
# example_img=np.array([[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,1,1,0,0],[0,0,0,0,0,0],[0,0,1,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0]])
# print(example_img)
# print(np.nonzero(example_img))
# print(np.nonzero(example_img)[0][0]-1) #r1
# print(np.nonzero(example_img)[1][0]-1) #c1
# print(np.nonzero(example_img)[0][-1]+1) #r2
# print(np.max(np.nonzero(example_img)[1])+1) #c2
# ---------------------------------

# print(bbox(img))

**23.Write a function to compute the average over a sliding window of length N over a 1D array?** Greg

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [50]:
def moving_average(x,N = 3):
    #define your function here
    try:
        a = np.reshape(x, (x.size//N, N))
    except:
        return f'Incompatible array size of {x.size} for sliding window of length {N}.'
    b = np.mean(a, axis=1)
    return b

a = np.arange(30)
N = 3
print(moving_average(a,N))

[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?** Michael

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [51]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include your solution here
A = np.repeat(np.arange(C.size), C)
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


**25. Find the most frequent value in the array below?** Meet

In [52]:
Z = np.random.randint(0,10,50)
# Include your solution below
countNum = np.bincount(Z)
print("The random array has following values")
print(Z)
print("The most frequently repeated value is -",np.argmax(countNum))
print("The number of times the value repeats is -",countNum[np.argmax(countNum)])

The random array has following values
[0 9 5 7 3 4 7 2 7 2 7 0 2 1 4 9 8 2 0 7 4 4 1 2 4 7 8 7 8 6 0 9 6 6 9 4 4
 6 0 6 5 9 0 8 3 0 8 1 8 2]
The most frequently repeated value is - 0
The number of times the value repeats is - 7


**26. Write a function to return the n largest values of an array** Brandon

In [53]:
def nlargest(a,n = 5):
    # Include your solution here
    # Uses np.sort to sort the array, then returns the last 5 elements of the sorted array
    a = np.sort(a)
    a = a[-n:]
    return a

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    

[9995 9996 9997 9998 9999]
